In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0  0.617184 -0.909700 -0.024479
1  0.023373 -0.711920  1.406442
2  1.067126  0.543400  1.518216
3 -1.204287 -0.589444  0.565858

In [14]:
dframe2

Y         Q         X
0 -0.400826 -0.351909 -1.637517
1  0.318809 -1.696591  0.354269
2 -0.382341  0.451379  0.269473

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.617184 -0.909700 -0.024479
1       NaN  0.023373 -0.711920  1.406442
2       NaN  1.067126  0.543400  1.518216
3       NaN -1.204287 -0.589444  0.565858
0 -0.351909 -1.637517 -0.400826       NaN
1 -1.696591  0.354269  0.318809       NaN
2  0.451379  0.269473 -0.382341       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.617184 -0.909700 -0.024479
1       NaN  0.023373 -0.711920  1.406442
2       NaN  1.067126  0.543400  1.518216
3       NaN -1.204287 -0.589444  0.565858
4 -0.351909 -1.637517 -0.400826       NaN
5 -1.696591  0.354269  0.318809       NaN
6  0.451379  0.269473 -0.382341       NaN

In [ ]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'